"""Unified database layer for CivicLens SaaS.

Supports both SQLite (development / single-instance) and PostgreSQL
(production / multi-instance) through a single DatabaseManager interface.

Backend selection is driven by the ``DATABASE_URL`` environment variable:
- Absent or ``sqlite:///path`` -> SQLite via the stdlib ``sqlite3`` module.
- ``postgresql://...``          -> PostgreSQL via ``psycopg2`` with connection
                                   pooling (``psycopg2.pool``).

Usage::

    from api.database import get_database, init_database

    # At application startup
    db = init_database(output_dir="/data/civiclens")

    # Elsewhere
    db = get_database()
    rows = db.fetch_all("SELECT * FROM tenants WHERE plan = %s", ("pro",))
"""

import importlib
import logging
import os
import pkgutil
import sqlite3
import threading
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# SQL dialect helpers
# ---------------------------------------------------------------------------

_SQLITE_PLACEHOLDER = "?"
_PG_PLACEHOLDER = "%s"


def _sqlite_to_pg(sql: str) -> str:
    """Convert ``?`` placeholders to ``%s`` for psycopg2.

    This is intentionally simple: it only replaces ``?`` that are *not*
    inside single-quoted string literals.  Covers all SQL generated by
    CivicLens stores (which never embed ``?`` in literals).
    """
    out: list[str] = []
    in_string = False
    for ch in sql:
        if ch == "'" and not in_string:
            in_string = True
            out.append(ch)
        elif ch == "'" and in_string:
            in_string = False
            out.append(ch)
        elif ch == "?" and not in_string:
            out.append("%s")
        else:
            out.append(ch)
    return "".join(out)


# ---------------------------------------------------------------------------
# DatabaseManager
# ---------------------------------------------------------------------------


class DatabaseManager:
    """Unified database interface for SQLite and PostgreSQL.

    Thread-safe.  For SQLite, uses a single shared connection with WAL
    journaling.  For PostgreSQL, uses a ``SimpleConnectionPool`` (min 2,
    max 10) and returns connections per-call.
    """

    def __init__(self, database_url: str, output_dir: str = "."):
        self._database_url = database_url
        self._output_dir = output_dir
        self._is_postgres = database_url.startswith("postgresql://")
        self._lock = threading.Lock()

        # Populated by _connect()
        self._pool = None            # psycopg2 pool (Postgres only)
        self._sqlite_conn = None     # sqlite3.Connection (SQLite only)

        self._connect()
        self._ensure_migrations_table()
        self.run_migrations()

    # ------------------------------------------------------------------
    # Dialect properties (used by migration files)
    # ------------------------------------------------------------------

    @property
    def is_postgres(self) -> bool:
        return self._is_postgres

    @property
    def serial_type(self) -> str:
        """Auto-incrementing integer primary key."""
        return "SERIAL PRIMARY KEY" if self._is_postgres else "INTEGER PRIMARY KEY AUTOINCREMENT"

    @property
    def real_type(self) -> str:
        return "DOUBLE PRECISION" if self._is_postgres else "REAL"

    @property
    def bool_type(self) -> str:
        return "BOOLEAN" if self._is_postgres else "INTEGER"

    @property
    def now_func(self) -> str:
        return "NOW()" if self._is_postgres else "datetime('now')"

    @property
    def conflict_clause(self) -> str:
        """Return the appropriate upsert preamble.

        SQLite: ``INSERT OR REPLACE``
        PostgreSQL: ``INSERT ... ON CONFLICT``  (caller must add the rest)
        """
        return "ON CONFLICT" if self._is_postgres else "ON CONFLICT"

    @property
    def placeholder(self) -> str:
        """Parameter placeholder character."""
        return _PG_PLACEHOLDER if self._is_postgres else _SQLITE_PLACEHOLDER

    # ------------------------------------------------------------------
    # Connection management
    # ------------------------------------------------------------------

    def _connect(self):
        if self._is_postgres:
            self._connect_postgres()
        else:
            self._connect_sqlite()

    def _connect_sqlite(self):
        """Open (or create) a SQLite database."""
        # If DATABASE_URL looks like sqlite:///path, strip the prefix.
        url = self._database_url
        if url.startswith("sqlite:///"):
            db_path = url[len("sqlite:///"):]
        elif url.startswith("sqlite://"):
            db_path = url[len("sqlite://"):]
        else:
            # Default: place civiclens.db inside the output directory
            db_path = os.path.join(self._output_dir, "civiclens.db")

        os.makedirs(os.path.dirname(db_path) or ".", exist_ok=True)

        self._sqlite_conn = sqlite3.connect(db_path, check_same_thread=False)
        self._sqlite_conn.row_factory = sqlite3.Row
        self._sqlite_conn.execute("PRAGMA journal_mode=WAL")
        self._sqlite_conn.execute("PRAGMA foreign_keys=ON")
        self._sqlite_conn.commit()
        logger.info("database_connected backend=sqlite path=%s", db_path)

    def _connect_postgres(self):
        """Create a PostgreSQL connection pool."""
        try:
            from psycopg2 import pool as pg_pool
        except ImportError:
            raise RuntimeError(
                "psycopg2 is required for PostgreSQL support. "
                "Install it with: pip install psycopg2-binary  "
                "(or add 'postgres' extras to pyproject.toml)"
            )

        self._pool = pg_pool.SimpleConnectionPool(
            minconn=2,
            maxconn=int(os.environ.get("DB_POOL_MAX", "10")),
            dsn=self._database_url,
        )
        logger.info(
            "database_connected backend=postgresql pool_min=2 pool_max=%s",
            os.environ.get("DB_POOL_MAX", "10"),
        )

    @contextmanager
    def _get_conn(self):
        """Yield a database connection.

        For SQLite this is the single shared connection (guarded by a lock).
        For PostgreSQL a connection is obtained from the pool and returned
        after the block.
        """
        if self._is_postgres:
            conn = self._pool.getconn()
            try:
                yield conn
            finally:
                self._pool.putconn(conn)
        else:
            with self._lock:
                yield self._sqlite_conn

    # ------------------------------------------------------------------
    # Core query API
    # ------------------------------------------------------------------

    def execute(self, sql: str, params: tuple | list = ()) -> Any:
        """Execute a single statement (INSERT / UPDATE / DELETE / DDL).

        Returns the cursor (useful for ``lastrowid`` / ``rowcount``).
        """
        sql = self._adapt_sql(sql)
        params = tuple(params)
        with self._get_conn() as conn:
            cursor = conn.cursor()
            cursor.execute(sql, params)
            conn.commit()
            return cursor

    def executescript(self, sql: str) -> None:
        """Execute multiple semicolon-separated statements.

        On PostgreSQL this runs the whole script in a single transaction.
        On SQLite this delegates to ``connection.executescript()``.
        """
        if self._is_postgres:
            sql_adapted = _sqlite_to_pg(sql)
            with self._get_conn() as conn:
                cursor = conn.cursor()
                cursor.execute(sql_adapted)
                conn.commit()
        else:
            with self._lock:
                self._sqlite_conn.executescript(sql)
                self._sqlite_conn.commit()

    def fetch_one(self, sql: str, params: tuple | list = ()) -> Optional[dict]:
        """Fetch a single row as a dict, or None."""
        sql = self._adapt_sql(sql)
        params = tuple(params)
        with self._get_conn() as conn:
            cursor = conn.cursor()
            cursor.execute(sql, params)
            row = cursor.fetchone()
            if row is None:
                return None
            if self._is_postgres:
                columns = [desc[0] for desc in cursor.description]
                return dict(zip(columns, row))
            else:
                return dict(row)

    def fetch_all(self, sql: str, params: tuple | list = ()) -> list[dict]:
        """Fetch all rows as a list of dicts."""
        sql = self._adapt_sql(sql)
        params = tuple(params)
        with self._get_conn() as conn:
            cursor = conn.cursor()
            cursor.execute(sql, params)
            rows = cursor.fetchall()
            if self._is_postgres:
                columns = [desc[0] for desc in cursor.description]
                return [dict(zip(columns, row)) for row in rows]
            else:
                return [dict(row) for row in rows]

    def fetch_scalar(self, sql: str, params: tuple | list = ()) -> Any:
        """Fetch a single scalar value (first column of first row)."""
        sql = self._adapt_sql(sql)
        params = tuple(params)
        with self._get_conn() as conn:
            cursor = conn.cursor()
            cursor.execute(sql, params)
            row = cursor.fetchone()
            if row is None:
                return None
            if self._is_postgres:
                return row[0]
            else:
                # sqlite3.Row supports index access
                return row[0]

    # ------------------------------------------------------------------
    # Transaction helper
    # ------------------------------------------------------------------

    @contextmanager
    def transaction(self):
        """Explicit transaction context manager.

        Commits on success, rolls back on exception.  For SQLite, also
        acquires the write lock for the duration.

        Usage::

            with db.transaction() as conn:
                conn.execute("INSERT INTO ...", (...))
                conn.execute("UPDATE ...", (...))
        """
        if self._is_postgres:
            conn = self._pool.getconn()
            try:
                yield conn
                conn.commit()
            except Exception:
                conn.rollback()
                raise
            finally:
                self._pool.putconn(conn)
        else:
            with self._lock:
                try:
                    yield self._sqlite_conn
                    self._sqlite_conn.commit()
                except Exception:
                    self._sqlite_conn.rollback()
                    raise

    # ------------------------------------------------------------------
    # Migration system
    # ------------------------------------------------------------------

    def _ensure_migrations_table(self):
        """Create the schema_migrations table if it does not exist."""
        ddl = """
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version     INTEGER PRIMARY KEY,
                name        TEXT NOT NULL,
                applied_at  TEXT NOT NULL
            )
        """
        if self._is_postgres:
            with self._get_conn() as conn:
                cur = conn.cursor()
                cur.execute(ddl)
                conn.commit()
        else:
            with self._lock:
                self._sqlite_conn.execute(ddl)
                self._sqlite_conn.commit()

    def _applied_versions(self) -> set[int]:
        """Return the set of already-applied migration version numbers."""
        rows = self.fetch_all("SELECT version FROM schema_migrations")
        return {row["version"] for row in rows}

    def run_migrations(self):
        """Discover and apply any pending migration files.

        Migration modules live in ``api/migrations/`` and are named
        ``NNN_description.py`` (e.g. ``001_initial.py``).  Each module
        must define ``up(db)`` and optionally ``down(db)``.
        """
        migrations_dir = Path(__file__).parent / "migrations"
        if not migrations_dir.is_dir():
            logger.debug("No migrations directory found at %s", migrations_dir)
            return

        applied = self._applied_versions()

        # Discover migration modules sorted by version number
        candidates: list[tuple[int, str, str]] = []
        for info in pkgutil.iter_modules([str(migrations_dir)]):
            name = info.name
            parts = name.split("_", 1)
            if not parts[0].isdigit():
                continue
            version = int(parts[0])
            candidates.append((version, name, str(migrations_dir / f"{name}.py")))

        candidates.sort(key=lambda c: c[0])

        for version, mod_name, mod_path in candidates:
            if version in applied:
                continue

            logger.info("Applying migration %03d (%s)...", version, mod_name)
            spec = importlib.util.spec_from_file_location(
                f"api.migrations.{mod_name}", mod_path
            )
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            if not hasattr(module, "up"):
                logger.warning("Migration %s has no up() function, skipping.", mod_name)
                continue

            module.up(self)

            # Record that this migration has been applied
            from datetime import datetime, timezone

            now = datetime.now(timezone.utc).isoformat()
            self.execute(
                "INSERT INTO schema_migrations (version, name, applied_at) VALUES (?, ?, ?)",
                (version, mod_name, now),
            )
            logger.info("Migration %03d applied successfully.", version)

    def rollback_migration(self, version: int):
        """Roll back a specific migration version (calls its ``down()``).

        Intended for development use.  In production, prefer forward-only
        migrations.
        """
        migrations_dir = Path(__file__).parent / "migrations"
        applied = self._applied_versions()

        if version not in applied:
            logger.warning("Migration %03d is not applied, nothing to rollback.", version)
            return

        # Find the module
        for info in pkgutil.iter_modules([str(migrations_dir)]):
            parts = info.name.split("_", 1)
            if parts[0].isdigit() and int(parts[0]) == version:
                mod_path = str(migrations_dir / f"{info.name}.py")
                spec = importlib.util.spec_from_file_location(
                    f"api.migrations.{info.name}", mod_path
                )
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)

                if not hasattr(module, "down"):
                    raise RuntimeError(f"Migration {info.name} has no down() function.")

                logger.info("Rolling back migration %03d (%s)...", version, info.name)
                module.down(self)
                self.execute("DELETE FROM schema_migrations WHERE version = ?", (version,))
                logger.info("Migration %03d rolled back.", version)
                return

        raise ValueError(f"Migration file for version {version} not found.")

    # ------------------------------------------------------------------
    # SQL dialect adaptation
    # ------------------------------------------------------------------

    def _adapt_sql(self, sql: str) -> str:
        """Adapt SQL from SQLite-style ``?`` placeholders to the active
        backend's placeholder if needed.
        """
        if self._is_postgres:
            return _sqlite_to_pg(sql)
        return sql

    # ------------------------------------------------------------------
    # Health / info
    # ------------------------------------------------------------------

    def health_check(self) -> dict:
        """Return a health-check dict suitable for an API ``/health`` endpoint."""
        backend = "postgresql" if self._is_postgres else "sqlite"
        try:
            self.fetch_scalar("SELECT 1")
            return {"status": "ok", "backend": backend}
        except Exception as e:
            return {"status": "error", "backend": backend, "error": str(e)}

    def table_stats(self) -> dict[str, int]:
        """Return row counts for every application table."""
        tables = [
            "tenants", "query_events", "meeting_processed_events",
            "api_call_events", "audit_log", "audit_retention_policies",
            "webhooks", "webhook_deliveries", "schedules", "job_history",
            "sso_config", "sso_users", "alerts", "alert_matches",
            "votes", "financial_items", "push_subscriptions", "branding",
            "health_snapshots", "export_jobs", "foia_requests",
        ]
        stats = {}
        for table in tables:
            try:
                count = self.fetch_scalar(f"SELECT COUNT(*) FROM {table}")
                stats[table] = count or 0
            except Exception:
                stats[table] = -1  # table may not exist yet
        return stats

    # ------------------------------------------------------------------
    # Cleanup
    # ------------------------------------------------------------------

    def close(self):
        """Close all connections / the pool."""
        if self._is_postgres and self._pool:
            self._pool.closeall()
            logger.info("PostgreSQL connection pool closed.")
        elif self._sqlite_conn:
            self._sqlite_conn.close()
            logger.info("SQLite connection closed.")


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

_database: Optional[DatabaseManager] = None


def init_database(output_dir: str = ".", database_url: Optional[str] = None) -> DatabaseManager:
    """Initialize the global database singleton.

    ``database_url`` defaults to the ``DATABASE_URL`` environment variable.
    If that is also unset, falls back to a SQLite database at
    ``{output_dir}/civiclens.db``.
    """
    global _database

    if database_url is None:
        database_url = os.environ.get("DATABASE_URL", "")

    if not database_url:
        db_path = os.path.join(output_dir, "civiclens.db")
        database_url = f"sqlite:///{db_path}"

    _database = DatabaseManager(database_url=database_url, output_dir=output_dir)
    return _database


def get_database() -> DatabaseManager:
    """Return the global DatabaseManager singleton.

    Raises RuntimeError if ``init_database()`` has not been called.
    """
    if _database is None:
        raise RuntimeError(
            "Database not initialized. Call init_database() at application startup."
        )
    return _database
